# Generated by Django 5.1.7 on 2025-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('conteudo', models.TextField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
