# Generated by Django 5.1.7 on 2025-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_postagem_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
