# Generated by Django 5.1.7 on 2025-03-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
