# Generated by Django 5.1.2 on 2025-03-10 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HairStyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='criado_em2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
