# Generated by Django 5.1.7 on 2025-03-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HairStyle', '0002_produto_criado_em2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
