# Generated by Django 5.1.7 on 2025-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HairStyle', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('profissional', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
