# Generated by Django 5.1.7 on 2025-03-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HairStyle', '0005_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='profissional',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
